// COLORS

export const colors = {
  COLOR_PRIMARY: 'black',
  COLOR_PRIMARY_BACK: 'white',
  COLOR_BUTTON: 'black',
  COLOR_INPUT_PLACEHOLDER: 'darkgray',
  COLOR_ACTIVE: 'royalblue',
  COLOR_SUCCESS: 'green',
  COLOR_BORDER: 'silver',
  COLOR_BACK_ACTIVE: '#F5F5F5'
};

// SIZES

export const sizes = {
  HEIGHT_GENERAL: 70,
  HEIGHT_ELEMENTS: 50,
  PADDING_LARGE: 20,
  PADDING_GENERAL: 15,
  PADDING_SMALL: 10,
  RADIUS_ELEMENTS: 16,
  RADIUS_SMALL_ELEMENTS: 10,
  RADIUS_ITEMS: 20,
  BORDER_THIN: 0.5
};

// TEXT STYLES

export const textSizes = {
  HEADER1: 26,
  HEADER2: 22,
  HEADER3: 18,
  PARAGRAPH: 16,
  SMALL: 12
};

// BACKGROUND COLORS

export const backgroundColors = {
  BACK_FORGOT_PASSWORD: colors.COLOR_PRIMARY_BACK,
  BACK_SIGNIN: colors.COLOR_PRIMARY_BACK,
  BACK_SIGNUP: colors.COLOR_PRIMARY_BACK
};
